spring:
  application:
    name: cambio-service
    jpa:
      database: POSTGRESQL
      show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    jackson:
      date-format: dd-MM-yyyy
      deserialization:
        fail-on-unknown-properties: false
    datasource:
      url: jdbc:postgresql://localhost:5429/cambio
      username: cambio
      password: cambio
    liquibase:
      change-log: classpath:/liquibase/master.xml
server:
  port: 8086